'on': workflow_dispatch
name: Deploy to Porter
jobs:
  porter-deploy:
    runs-on: ubuntu-runner-32gb
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Github tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build Image
      timeout-minutes: 20
      uses: porter-dev/porter-cli-action@v0.1.0
      with:
        command: update build --app cal-com --tag ${{ steps.vars.outputs.sha_short }} --stream
      env:
        PORTER_HOST: https://dashboard.getporter.dev
        PORTER_CLUSTER: 2444
        PORTER_PROJECT: 6657
        PORTER_TOKEN: ${{ secrets.PORTER_TOKEN_6657 }}

    - name: Push Image
      timeout-minutes: 20
      uses: porter-dev/porter-cli-action@v0.1.0
      with:
        command: update push --app cal-com --tag ${{ steps.vars.outputs.sha_short }} --stream
      env:
        PORTER_HOST: https://dashboard.getporter.dev
        PORTER_CLUSTER: 2444
        PORTER_PROJECT: 6657
        PORTER_TOKEN: ${{ secrets.PORTER_TOKEN_6657 }}

    - name: Update cal-com App
      timeout-minutes: 20
      uses: porter-dev/porter-cli-action@v0.1.0
      with:
        command: update config --app cal-com --tag ${{ steps.vars.outputs.sha_short }} --stream
      env:
        PORTER_HOST: https://dashboard.getporter.dev
        PORTER_CLUSTER: 2444
        PORTER_PROJECT: 6657
        PORTER_TOKEN: ${{ secrets.PORTER_TOKEN_6657 }}

    - name: Update cal-com-api App
      timeout-minutes: 20
      uses: porter-dev/porter-cli-action@v0.1.0
      with:
        command: update config --app cal-com-api --tag ${{ steps.vars.outputs.sha_short }} --stream
      env:
        PORTER_HOST: https://dashboard.getporter.dev
        PORTER_CLUSTER: 2444
        PORTER_PROJECT: 6657
        PORTER_TOKEN: ${{ secrets.PORTER_TOKEN_6657 }}
